language: python
python:
  - "3.6"
  # - pip install .
  # - sudo apt-get update
  # # We do this conditionally because it saves us some downloading if the
  # # version is the same.
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #   else
  #     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - export PATH="$HOME/miniconda/bin:$PATH"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # # Useful for debugging any issues with conda
  # - conda info -a

  # - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  # - source activate test-environment

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/shared
  - aws s3 sync s3://travis-build-stages-shared-storage-test/shared ~/shared

# see for alternatives to travis wait
# https://github.com/travis-ci/travis-ci/issues/4190

# split tests into stages to avoid 50 mins time limit
# https://docs.travis-ci.com/user/build-stages/
jobs:
  include:
    - stage: "install and setup coverage call"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - bash bin/createGraphLibFile.sh
    - stage: "test loading and algorithms"
      install: skip
      script:
        # Output something every 10 minutes or Travis kills the job
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_load.py
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_algs.py
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_crd.py
        # Killing background sleep loop
        - kill %1
    - stage: "test ncp and plots"
      install: skip
      script:
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_ncp.py
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_plots.py
        - kill %1
    - stage: "test notebooks"
      install: skip
      script:
        - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - coverage run -p --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest --notebook-tests --test-plots --long-tests localgraphclustering/tests/test_notebook.py
        - kill %1
    - stage: "combine test data"
      install: skip
      script:
        - coverage combine
after_success:
  - aws s3 sync ~/shared s3://travis-build-stages-shared-storage-test/shared
  coveralls
