language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - bash bin/createGraphLibFile.sh
# command to run tests
script: coverage run --source=localgraphclustering --omit=localgraphclustering/tests/* -m pytest localgraphclustering/tests/
after_success:
  coveralls