language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - bash bin/createGraphLibFile.sh
# command to run tests
script: pytest localgraphclustering/tests/
before_install:
  - pip install codecov
after_success:
  - codecov --file coverage/lcov.info --disable search